site_name: MkDocsとGitHub Pages

theme:
  name: 'material'
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: 'teal'
      accent: 'teal'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: 'teal'
      accent: 'teal'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_alt

plugins:
    - search
    - awesome-pages


repo_url: https://github.com/akikuno/mkdocs-and-ghpages
repo_name: akikuno/mkdocs-and-ghpages

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/akikuno_sh
      name: akikuno on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/akikuno/

copyright: "&copy; 2023- akikuno"
