site_name: MkDocsとGitHub Pages
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'

markdown_extensions:
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_alt

plugins:
    - search
    - awesome-pages


repo_url: https://github.com/akikuno/blog-test-mkdocs
repo_name: akikuno/blog-test-mkdocs

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/akikuno_sh
      name: akikuno on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/akikuno/

copyright: "&copy; 2023- akikuno"
